#!/usr/bin/env python3

import sys
import requests

on_cmd = ["on", "off", "tog", "toggle", "t"]
inc_cmd = ["up", "increase", "inc"]
dec_cmd = ["down", "decrease", "dec"]

def log_help():
    print(f"usage: ac [COMMAND]\ncommands:\t{on_cmd}\n\t\t{inc_cmd}\n\t\t{dec_cmd}")

def main():
    if len(sys.argv) != 2:
        log_help();
        sys.exit(1)

    cmd = sys.argv[1]
    addr = "http://192.168.1.207"

    if cmd in on_cmd:
        # print("toggling on/off")
        requests.get(f"{addr}/tog")
    elif cmd in inc_cmd:
        # print("up")
        requests.get(f"{addr}/inc")
    elif cmd in dec_cmd:
        # print("down")
        requests.get(f"{addr}/dec")
    else:
        print("unknown command\n")
        log_help();
        sys.exit(1)

if __name__ == "__main__":
    main()
