const char* webpage =  "<!DOCTYPE html>"
 "<html lang=\"en\">"
 "  <head>"
 "    <meta charset=\"UTF-8\">"
 "	<meta name=\"viewport\" content=\"width=device-width, user-scalable=no\">"
 "    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">"
 "	<title>ac thing</title>"
 "	<style>"
 "		:root { color-scheme: dark; }"
 "		body, html {"
 "			text-align: center;"
 "			height: 100%;"
 "			overflow: hidden;"
 "			font-family: system-ui;"
 "			background: black"
 "		}"
 "		#wrapper {"
 "			height: 95%;"
 "			align-content: center;"
 "		}"
 "		button {"
 "			font-size: 2.5em;"
 "			width: 7em;"
 "			height: 1.7em;"
 "			margin-bottom: 0.5em;"
 "			border-radius: 0px;"
 "			color: white;"
 "			text-shadow: 0px 0px 8px rgba(255,255,255,0.7);"
 "			background: linear-gradient(to bottom, #444, #000);"
 "			border: 1px solid #333;"
 "			font-weight: bold;"
 "			font-family: system-ui;"
 "		}"
 "		#ac-thing {"
 "			color: grey;"
 "			font-weight: bold;"
 "			font-style: italic;"
 "			text-shadow: 0px 0px 8px rgba(255,255,255,0.7);"
 "		}"
 "	</style>"
 "  </head>"
 "  <body>"
 "  	<div id=\"wrapper\">"
 "		<button onclick=\"fetch('/tog')\">on/off</button> <br />"
 "		<button onclick=\"fetch('/inc')\">increase</button> <br />"
 "		<button onclick=\"fetch('/dec')\">decrease</button> <br />"
 "	</div>"
 ""
 "	<div id=\"ac-thing\">ac thing</div>"
 "  </body>"
 "</html>"
 ""
;